apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: nopejs
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jrichter/nodejs:5dce2b0716be044e48c8130c1fe22c28d4a3c3fb@sha256:bf3bb9e513796678d06233650194ba96134b56c7981efaa2b74635e50fdb44f4
        name: container-image  
